---
# Variable configuration.
- include: variables.yml

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  static: no

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  static: no

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed) or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed) }}"

# Configure MySQL.
- include: configure.yml
- include: secure-installation.yml
- include: databases.yml
- include: users.yml
- include: replication.yml

# For MB
# Copy dump scripts
# Has to be after the root password assignment, for idempotency.
- name: Copy mysql-export-data.sh
  template:
    src: "mysql-export-data.sh"
    dest: "/usr/local/bin/mysql-export-data"
    owner: root
    group: root
    mode: 0777

# Has to be after the root password assignment, for idempotency.
- name: Copy mysql-export-users.php
  template:
    src: "mysql-export-users.php"
    dest: "/usr/local/bin/mysql-export-users"
    owner: root
    group: root
    mode: 0777