---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"

# Configure MySQL.
- include_tasks: configure.yml
- include_tasks: secure-installation.yml
- include_tasks: databases.yml
- include_tasks: users.yml
- include_tasks: replication.yml

# For MB
# Copy dump scripts
# Has to be after the root password assignment, for idempotency.
- name: Copy mysql-export-data.sh
  template:
    src: "mysql-export-data.sh"
    dest: "/usr/local/bin/mysql-export-data"
    owner: root
    group: root
    mode: 0777

# Has to be after the root password assignment, for idempotency.
- name: Copy mysql-export-users.php
  template:
    src: "mysql-export-users.php"
    dest: "/usr/local/bin/mysql-export-users"
    owner: root
    group: root
    mode: 0777